### ISSUE TITLE
Can I connect this to a Foxalien Masuter Pro?

### ISSUE THREAD

**Issue by brandoncordell** [ThunderCNC/GRBL_SPD#1]
I opened up my Master Pro controller today and saw that I have an empty 3-pin PWM socket. If I supply GRBLSPD with 5.5v and connect this up like the instructions layout, will it work?

**Comment by ThunderCNC** [comment]
Hi Brandon,
I was trying to find a circuit diagram for your cnc but could not find one. If the pwm on your controller is 5v max and it has a 5v power rail to supply the GRBL_SPD it should work.

**Comment by brandoncordell** [comment]
Thanks! If the PWM is more than 5v, would it be safe to add resistors or a buck converter inline to get it down to 5v? I'll pull out the multimeter in the morning. Thanks so much!

**Comment by ThunderCNC** [comment]
No worries. Anytime. 5.5v is max for the microcontroller. I would be hesitant on running that voltage. I’ve seen on other controllers the pwm being labeled ttl. If so it should be 5v max. If need be a resistor voltage divider would work with little to no error. Buck would probably distort the signal too much. Also if your setup allows the pwm should be set for 1kHz if possible. 
In the version 5 I used optocouplers to accept multiple voltage levels and a bunch of filtering but they won’t be available for a couple months. Version 4 will be available the end of the month but it is the same layout as V3, just faster. 
Cheers!

**Comment by brandoncordell** [comment]
Pulled out the multimeter today after getting some free time and it looks like the available power rails are 12v and 48v. The PWM is 12v as well. I think 4.8k ohm and 6.8k ohm resistors will get me down to 5v. Hopefully that will work out. 

> Buck would probably distort the signal too much.

Was this in regards to just the PWM? Can I use one for just powering the microcontroller?

**Comment by ThunderCNC** [comment]
Yes I was referring to the pwm. A buck on the either of the two power rails to power it would be fine but 12v would be preferred. Resistor values you stated look good. Another option would be to use a mosfet level shifter for the pwm.
